[env:esp32cam]
platform = espressif32
board = esp32cam
framework = arduino

; Serial Monitor Baud Rate
monitor_speed = 115200

; Upload Speed
upload_speed = 921600

; Partition table (ESP32-CAM needs huge app space for camera drivers)
board_build.partitions = huge_app.csv

; Build flags to enable C++17 and optimization
build_flags =
    -D CORE_DEBUG_LEVEL=3
    -std=gnu++17